### ISSUE TITLE
App crashes once when opening

### ISSUE THREAD

**Issue by LeoColman** [LeoColman/Petals#316]
After 3.9, petals crashes after (it seems) reopening it after some time.

**Comment by LeoColman** [comment]
> FATAL EXCEPTION: main
Process: br.com.colman.petals, PID: 3958
java.lang.RuntimeException: java.lang.NoSuchMethodException: B.J0.values []
 at java.lang.Enum.enumValues(Enum.java:272)
 at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
 at java.lang.Enum$1.create(Enum.java:279)


Got the crash log. Without mappings it's not very useful.

**Comment by LeoColman** [comment]
Anecdotally, it seems to happen when coming back to the Usage screen.

When maximizing from the statistics page it doesn't crash. Or at least not as usual for me to notice.

**Comment by LeoColman** [comment]
```
FATAL EXCEPTION: main
Process: br.com.colman.petals, PID: 24801
java.lang.RuntimeException: java.lang.NoSuchMethodException: androidx.compose.material.DrawerValue.values []
 at java.lang.Enum.enumValues(Enum.java:272)
 at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
 at java.lang.Enum$1.create(Enum.java:279)
 at java.lang.Enum$1.create(Enum.java:277)
 at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
 at java.lang.Enum.getSharedConstants(Enum.java:291)
 at java.lang.Enum.valueOf(Enum.java:245)
 at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1869)
 at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1437)
 at java.io.ObjectInputStream.readObject(ObjectInputStream.java:428)
 at android.os.Parcel.readSerializableInternal(Parcel.java:5098)
 at android.os.Parcel.readValue(Parcel.java:4639)
 at android.os.Parcel.readValue(Parcel.java:4347)
 at android.os.Parcel.readListInternal(Parcel.java:5329)
 at android.os.Parcel.readArrayListInternal(Parcel.java:5348)
 at android.os.Parcel.readValue(Parcel.java:4597)
 at android.os.Parcel.readValue(Parcel.java:4347)
 at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
 at android.os.Parcel$LazyValue.apply(Parcel.java:4445)
 at android.os.Parcel$LazyValue.apply(Parcel.java:4404)
 at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
 at android.os.BaseBundle.getValue(BaseBundle.java:374)
 at android.os.BaseBundle.getValue(BaseBundle.java:357)
 at android.os.BaseBundle.getValue(BaseBundle.java:350)
 at android.os.Bundle.getParcelableArrayList(Bundle.java:1046)
 at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(SourceFile:255)
 at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:8)
 at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:2)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
 at androidx.compose.runtime.Updater.CompositionLocalProvider(Unknown Source:29)
 at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:7)
 at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:1)
 at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
 at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(SourceFile:64)
 at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(SourceFile:41)
 at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:130)
 at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Unknown Source:13)
 at androidx.compose.runtime.CompositionImpl.composeContent(SourceFile:18)
 at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(SourceFile:50)
 at androidx.compose.runtime.CompositionImpl.setContent(Unknown Source:10)
 at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(SourceFile:7)
 at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(Unknown Source:9)
 at androidx.compose.ui.platform.WrappedComposition.setContent(Unknown Source:13)
 at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Unknown Source:18)
 at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(SourceFile:23)
 at androidx.lifecycle.LifecycleRegistry.addObserver(SourceFile:111)
 at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(SourceFile:5)
 at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(SourceFile:114)
 at android.view.View.dispatchAttachedToWindow(View.java:21308)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2879)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2350)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9194)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
 at android.view.Choreographer.doCallbacks(Choreographer.java:899)
 at android.view.Choreographer.doFrame(Choreographer.java:832)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7884)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NoSuchMethodException: androidx.compose.material.DrawerValue.values []
 at java.lang.Class.getMethod(Class.java:2103)
 at java.lang.Class.getDeclaredMethod(Class.java:2081)
 at java.lang.Enum.enumValues(Enum.java:269)
 ... 69 more
```

Still clueless.

**Comment by LeoColman** [comment]
FATAL EXCEPTION: main
Process: br.com.colman.petals, PID: 12559
android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class T0.j
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4953)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4807)
	at android.os.Parcel.readParcelableArrayInternal(Parcel.java:5018)
	at android.os.Parcel.readValue(Parcel.java:4645)
	at android.os.Parcel.readValue(Parcel.java:4347)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4445)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4404)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
	at android.os.BaseBundle.getValue(BaseBundle.java:374)
	at android.os.BaseBundle.getValue(BaseBundle.java:357)
	at android.os.BaseBundle.getValue(BaseBundle.java:350)
	at android.os.Bundle.getParcelableArray(Bundle.java:975)
	at T0.u.J(SourceFile:23)
	at androidx.navigation.compose.w.t0(SourceFile:9)
	at O.b.b(SourceFile:117)
	at androidx.navigation.compose.q.i(SourceFile:42)
	at br.com.colman.petals.e.a(SourceFile:185)
	at br.com.colman.petals.e.f0(SourceFile:53)
	at N.f.f0(SourceFile:59)
	at androidx.compose.ui.platform.t0.a(Unknown Source:24)
	at androidx.compose.ui.platform.a.f0(SourceFile:40)
	at N.f.f0(SourceFile:59)
	at G.K.a(Unknown Source:29)
	at androidx.compose.ui.platform.u0.a(SourceFile:349)
	at androidx.compose.ui.platform.W.a(SourceFile:44)
	at androidx.compose.ui.platform.W.f0(SourceFile:17)
	at N.f.f0(SourceFile:59)
	at G.K.a(Unknown Source:29)
	at androidx.compose.ui.platform.b0.a(SourceFile:563)
	at androidx.compose.ui.platform.w1.a(SourceFile:36)
	at androidx.compose.ui.platform.w1.f0(SourceFile:17)
	at N.f.f0(SourceFile:59)
	at G.K.a(Unknown Source:29)
	at androidx.compose.ui.platform.w1.a(SourceFile:194)
	at androidx.compose.ui.platform.w1.f0(SourceFile:29)
	at N.f.f0(SourceFile:59)
	at G.K.X(Unknown Source:19)
	at G.J.J(SourceFile:136)
	at G.J.A(Unknown Source:13)
	at G.P.p(SourceFile:19)
	at G.c1.a(SourceFile:47)
	at G.P.d(Unknown Source:10)
	at androidx.compose.ui.platform.Z.t0(SourceFile:124)
	at androidx.compose.ui.platform.AndroidComposeView.K0(Unknown Source:9)
	at androidx.compose.ui.platform.WrappedComposition.d(Unknown Source:13)
	at androidx.compose.ui.platform.WrappedComposition.f(Unknown Source:18)
	at androidx.lifecycle.w.a(SourceFile:23)
	at androidx.lifecycle.x.a(SourceFile:111)
	at androidx.compose.ui.platform.Z.t0(SourceFile:86)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(SourceFile:114)
	at android.view.View.dispatchAttachedToWindow(View.java:21357)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2900)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NoSuchFieldException: CREATOR
	at java.lang.Class.getField(Class.java:1635)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4930)
	... 72 more

**Comment by LeoColman** [comment]
Finally seem to have found it
